### ISSUE TITLE
g:sortableColumn and g:datePicker does not render as expected.

### ISSUE THREAD

**Issue by ocomsoft** [groovydev/twitter-bootstrap-grails-plugin#3]
I was also working on a Plugin for the Twitter Bootstrap and I noticed that the SortableColumn tag doesn't generate html that work with the CSS. I created and other CSS file which I include in the Resources entry

Here is the css I added

``` css


/* Table Sorting */
th.asc a, th.desc a {
    background-position: right;
    background-repeat: no-repeat;
}
th.asc a {
    background-image: url(../images/skin/sorted_asc.gif);
}
th.desc a {
    background-image: url(../images/skin/sorted_desc.gif);
}

/* Date Picker CSS
The Hour and minute are untested... 
*/
select[name*='_day'], select[name*='_hour'], select[name*='_minute']  {
    width:50px;
}
select[name*='_month'] {
    width:100px;
}
select[name*='_year'] {
    width:75px;
}
```

I hope this helps.
